import { DarkSkyIcon } from "./icon";

export type DarkSkyDataPointObject = {
  time: number;
  summary?: string;
  icon?: DarkSkyIcon;
  sunriseTime?: number;
  sunsetTime?: number;
  moonPhase?: number;
  precipAccumulation?: number;
  precipIntensity?: number;
  precipIntensityMax?: number;
  precipIntensityMaxTime?: number;
  precipProbability?: number;
  precipType?: string;
  temperature?: number;
  temperatureHigh?: number;
  temperatureHighTime?: number;
  temperatureLow?: number;
  temperatureLowTime?: number;
  apparentTemperatureHigh?: number;
  apparentTemperatureHighTime?: number;
  apparentTemperatureLow?: number;
  apparentTemperatureLowTime?: number;
  dewPoint?: number;
  humidity?: number;
  pressure?: number;
  windSpeed?: number;
  windGust?: number;
  windGustTime?: number;
  windBearing?: number;
  cloudCover?: number;
  uvIndex?: number;
  uvIndexTime?: number;
  visibility?: number;
  ozone?: number;
  temperatureMin?: number;
  temperatureMinTime?: number;
  temperatureMax?: number;
  temperatureMaxTime?: number;
  apparentTemperature: number;
  apparentTemperatureMin?: number;
  apparentTemperatureMinTime?: number;
  apparentTemperatureMax?: number;
  apparentTemperatureMaxTime?: number;
  nearestStormBearing?: number;
  nearestStormDistance?: number;
};
